---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.23.7
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers,ref2vec-centroid'
      CLUSTER_HOSTNAME: 'node1'
    healthcheck:
      test: wget --no-verbose --tries=3 --spider http://localhost:8080/v1/.well-known/ready || exit 1
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 60s
  t2v-transformers:
    build:
      context: embedders
      dockerfile: bge-base-en-1.5.Dockerfile
    # image: semitechnologies/transformers-inference:sentence-transformers-paraphrase-multilingual-MiniLM-L12-v2
    ports:
      - 8080
    environment:
      ENABLE_CUDA: '1'
      NVIDIA_VISIBLE_DEVICES: 'all'
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: 
            - 'gpu'
  server:
    build:
      context: Server/Dispatcher
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      weaviate:
        condition: service_healthy
  admin_client:
    build:
      context: Client/Admin
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    depends_on:
      weaviate:
        condition: service_healthy
  user_client:
    build:
      context: Client/User
      dockerfile: Dockerfile
    ports:
      - 8500:8500
    depends_on:
      weaviate:
        condition: service_healthy
  ollama:
    image: "ollama/ollama"
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  weaviate_data:
  admin_data:
  ollama:
...